server:
  port: 8888
spring:
  application:
    name: tingshuo-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tingshuo-test
          #uri: lib://cloud-tingshuo-service
          uri: http://localhost:8080
          #断言
          predicates:
            - Path=/user/*
#注册中心相关配置
eureka:
  instance:
    # 应用实例主机名
    hostname: eurekaClient
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: true
  client:
    service-url:
      # Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://tingshuo:tingshuo123yz@127.0.0.1:8761/eureka
    instance:
      #模块之间跨域访问
      prefer-ip-address: true
    #false #是否将自己注册到Eureka服务中
    register-with-eureka: true
    #false #是否从Eureka中获取注册信息
    fetch-registry: true
