server:
  port: 9999
#spring连接源
spring:
  application:
    name: tingshuo-activity
  datasource:
    url: jdbc:postgresql://localhost:5432/pg_tingshuo
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
    # 进行日志采集
  sleuth:
    sampler:
        #日志采用级别1.0 表示全部采集
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411
      sender:
        type: web
#注册中心相关配置
eureka:
  instance:
    # 应用实例主机名
    hostname: tingshuo-activity
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: true
  client:
    service-url:
      # Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://tingshuo:tingshuo123yz@192.168.31.215:8761/eureka
    instance:
      instance-id: tingshuo-activity:9999
      #模块之间跨域访问
      prefer-ip-address: true
    #false #是否将自己注册到Eureka服务中
    register-with-eureka: false
    #false #是否从Eureka中获取注册信息
    fetch-registry: false





