server:
  port: 8888
spring:
  application:
    name: tingshuo-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #表示是否与“服务中心”的发现组件进行结合
          enabled: true
          #通过配置文件方式配置路由
      routes:
      #当访问到ip+8888/hello,将会请求到http://192.168.31.215:8080/hello服务上
      #自定义的路由id
        - id: tingshuo-gateway
      #uri: lb://cloud-tingshuo-service
      #目标服务注册中心的名称
          uri: lb://tingshuo-test
          #断言
          #路由条件，统一回调熔断地址
          predicates:
            - Path=/hello/**
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
        #配置统一不存在请求返回固定参数
        - id: Fault-Tolerance Routing
          uri: forward:/notfound
          predicates:
            - Path=/**
#熔断机制
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 2000


#注册中心相关配置
eureka:
  instance:
    # 应用实例主机名
    hostname: eurekaClient
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: true
  client:
    service-url:
      # Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://tingshuo:tingshuo123yz@192.168.31.215:8761/eureka
    instance:
      #模块之间跨域访问
      prefer-ip-address: true
    #false #是否将自己注册到Eureka服务中
    register-with-eureka: true
    #false #是否从Eureka中获取注册信息
    fetch-registry: true
logging:
  level:
    Root: info
