server:
  port: 8888
spring:
  application:
    name: tingshuo-gateway
  redis:
    #使用redis库进行限流
    database: 1
    host: 127.0.0.1
    #连接redis端口
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          #表示是否与“服务中心”的发现组件进行结合
          enabled: true
          #通过配置文件方式配置路由
#      routes:
#        #当访问到ip+8888/hello,将会请求到http://192.168.31.215:8080/hello服务上
#        #自定义的路由id
#        - id: tingshuo-gateway-ip
#          #目标服务注册中心名称
#          uri: lb://tingshuo-test
#          #断言
#          #路由条件
#          predicates:
#            - Path=/hello/**
#          filters:
#            #使用聂荣臻的令牌算法
#            - name: RequestRateLimiter
#              args:
#                #令牌补充的频率。每次就1个
#                 redis-rate-limiter.replenishRate: 1
#                #令牌桶的最大容量。即允许在1s内完成最大的请求数
#                 redis-rate-limiter.burstCapacity: 2
#                 key-resolver: "#{@ipKeyResolver}"



#注册中心相关配置
eureka:
  instance:
    # 应用实例主机名
    hostname: eurekaClient
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: true
  client:
    service-url:
      # Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://tingshuo:tingshuo123yz@192.168.31.215:8761/eureka
    instance:
      #模块之间跨域访问
      prefer-ip-address: true
    #false #是否将自己注册到Eureka服务中
    register-with-eureka: true
    #false #是否从Eureka中获取注册信息
    fetch-registry: true
logging:
  level:
    Root: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true


