server:
  port: 8888
spring:
  application:
    name: tingshuo-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #表示是否与“服务中心”的发现组件进行结合
          enabled: true
          #通过配置文件方式配置路由
      routes:
        #当访问到ip+8888/hello,将会请求到http://192.168.31.215:8080/hello服务上
        #自定义的路由id
        - id: tingshuo-gateway-hello
          #uri: lb://cloud-tingshuo-service
          #目标服务地址
          uri: http://192.168.31.215:8080
          #断言
          #路由条件
          predicates:
            - Path=/hello/**
            #- After=2022-02-17
            #- Before=2022-12-01
            #- Cookie=name,test
            #- Header=X-Request-Id,\d+
            #- Host=**.31.215:8080
            #- Method=GET
            #当请求正则
            #- Query=name#?name=x&id=1
            #当请求到name，其中.代表一个字段
            #- Query=name,test.
            #采用CIDR符号，192.168.31.1表示ip，255表示子网掩码
            #- RemoteAddr=192.168.31.1/255
            #当有10个请求，4个会访问到id: tingshuo-gateway-hello01 ,6个会访问到tingshuo-gateway-hello02
            #- Weigth=Weight,4
            #- Weight=Weight,6
        #自定义 未定义的路由，提示统一错误
        - id: Fault-Tolerance Routing
          uri: forward:/notfound
          predicates:
            - Path=/**


#注册中心相关配置
eureka:
  instance:
    # 应用实例主机名
    hostname: eurekaClient
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: true
  client:
    service-url:
      # Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://tingshuo:tingshuo123yz@192.168.31.215:8761/eureka
    instance:
      #模块之间跨域访问
      prefer-ip-address: true
    #false #是否将自己注册到Eureka服务中
    register-with-eureka: true
    #false #是否从Eureka中获取注册信息
    fetch-registry: true
logging:
  level:
    Root: info
