server:
  port: 9080
#spring连接源
spring:
  application:
    name: tingshuo-modules
  datasource:
    url: jdbc:postgresql://localhost:5432/pg_tingshuo
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
  # 进行日志采集
  sleuth:
    sampler:
      #日志采用级别1.0 表示全部采集
      probability: 1.0
  zipkin:
    base-url: http://192.168.31.215:9411
    sender:
      type: web
#使用注册中心的名字即可
tingshuo-activity:
  #使用ribbon 负载均衡
  ribbon:
    #配置随机策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #服务地址
    listOfServers: http://192.168.31.215:8888,http://192.168.31.215:9999

#注册中心相关配置
eureka:
  instance:
    # 应用实例主机名
    #hostname: eurekaClient
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: false
    ip-address: 127.0.0.1
  client:
    service-url:
      # Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://tingshuo:tingshuo123yz@192.168.31.215:8761/eureka
    instance:
      #模块之间跨域访问
      prefer-ip-address: true
    #false #是否将自己注册到Eureka服务中
    register-with-eureka: true
    #false #是否从Eureka中获取注册信息
    fetch-registry: true
#mybatis-plus设置
mybatis-plus:
    mapper-locations: classpath:mapper/*Mapper.xml
    configuration:
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      # 返回类型为Map,显示null对应的字段
      call-setters-on-nulls: true
# 设置日志打印记录
logging:
  level:
    org.springframework.cloud.sleuth: info
#开启熔断hystix支持
feign:
  hystrix:
    enabled: true
#开启监控页面
hystrix:
  dashboard:
    proxy-stream-allow-list: "192.168.31.215"
#开启监控服务中心列表，表明监控哪些服务
turbine:
  app-config: tingshuo-activity,tingshuo-test
  #聚合哪些集群，默认为default，多个,隔开
  aggregator:
    cluster-config: default
  # 集群名称，默认为应用名
  cluster-name-expression: new String("default")

#app
app:
  id: app001
#Apollo配置中心配置
apollo:
  #将服务信息，缓存到本地目录
  cache-dir: I:/app/data/
  #指定使用那个集群
  cluster: default
  #连接服务器的地址信息 即注册中心地址
  meta: http://localhost:8080
  #是否开启 spring参数自动更新
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    #是否开启apollo
    enabled: true
    #设置namespace
    namespaces: application
    eagerLoad:
      #将Apollo 加载提到初始化日志系统之前
      enabled: true
test: 1000

